{
 "title": "first_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ESP32",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n|> range(start: -1h)\r\n|> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"esp-device\" and r.source == \"humidity\")\r\n  "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n|> range(start: -1h)\r\n|> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"esp-device\" and r.source == \"temperature\")\r\n  "
    }
   ]
  },
  {
   "title": "illuminance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n|> range(start: -1h)\r\n|> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"esp-device\" and r.source == \"illuminance\")\r\n  "
    }
   ]
  },
  { "title": "Lc-algue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"lc-algue\" and r.source == \"temperature\")"
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"lc-algue\" and r.source == \"illuminance\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"lc-algue\" and r.source == \"humidity\")\r\n"
    }
   ]
  }
 ]
}