{
 "title": "first_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"counter_float\" and r.source == \"pressure\")"
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"counter_float\" and r.source == \"illuminance\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"counter_float\" and r.source == \"temperature\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"lemarconnect\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"counter_float\" and r.source == \"humidity\")\r\n"
    },
    {
     "query": "from(bucket: \"lemarconnect\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"measurement1\" and r._field == \"counter\" and r.source == \"humidity\")\r\n"
    }
   ]
  }
 ]
}